// Generated by scripts/sync_brand_assets.py from CITATION.cff and assets/project.json. Do not edit.
//
// Research provenance, shown in the hero (affiliation) and the footer colophon.
// The dataset licence is deliberately absent: it is planned, not published, and
// docs/src/content/docs/project/dataset.md is its one canonical statement.
export const research = {
  "affiliation": "A research platform of the Institute of Environmental Sciences (CML), Leiden University",
  "institution": "Institute of Environmental Sciences (CML), Leiden University",
  "authors": "Simon van Lierde and Franco Donati, Department of Industrial Ecology, CML",
  "citationUrl": "https://doi.org/10.5281/zenodo.16637742",
  "doi": "10.5281/zenodo.16637742",
  "licence": "AGPL-3.0-or-later",
  "licenceUrl": "https://github.com/CMLPlatform/relab/blob/main/LICENSE",
  "funding": "Leiden University Starter Fund; Depack grant (Leiden University Fund); Sectorplan Gelden"
} as const;
