shared:
  - '.github/**'
  - '.devcontainer/**'
  - '.vscode/**'
  - '.python-version'
  - '.env.example'
  - 'backend/.env*.example'
  - 'justfile'
  - 'scripts/**'
  - 'deploy/**'
  - 'compose*.yml'
  - 'compose*.yaml'

policy:
  - '.github/**'
  - '.pre-commit-config.yaml'
  - '.prettierrc*'
  - '.editorconfig'
  - '.devcontainer/**'
  - '.vscode/**'
  - '.python-version'
  - '.env.example'
  - 'backend/.env*.example'
  - 'pyproject.toml'
  - 'justfile'
  - 'scripts/**'
  - 'deploy/**'

backend:
  - 'backend/**'
  - 'compose*.yml'
  - 'compose*.yaml'

frontend-web:
  - 'frontend-web/**'
  - 'compose*.yml'
  - 'compose*.yaml'

frontend-app:
  - 'frontend-app/**'
  - 'compose*.yml'
  - 'compose*.yaml'

docs:
  - 'docs/**'
  - 'compose*.yml'
  - 'compose*.yaml'

containers:
  - 'compose*.yml'
  - 'compose*.yaml'
  - '**/Dockerfile*'
  - 'backend/uv.lock'
  - 'docs/pnpm-lock.yaml'
  - 'frontend-app/pnpm-lock.yaml'
  - 'frontend-web/pnpm-lock.yaml'
