"""Pairing endpoints for zero-config RPi camera registration.

Flow:
1. RPi generates a 6-char code and POSTs it to /register (unauthenticated).
2. User enters the code in the ReLab UI and POSTs to /claim (authenticated).
   Backend creates the camera and stores credentials in Redis.
3. RPi polls /poll until it receives credentials, then starts the relay.
"""

from __future__ import annotations

import json
import logging

from fastapi import Query, Request, status

from app.api.auth.dependencies import CurrentActiveUserDep
from app.api.auth.services.rate_limiter import limiter
from app.api.common.routers.dependencies import AsyncSessionDep
from app.api.common.routers.openapi import PublicAPIRouter
from app.api.plugins.rpi_cam import crud
from app.api.plugins.rpi_cam.exceptions import (
    PairingCodeAlreadyClaimedError,
    PairingCodeCollisionError,
    PairingCodeNotFoundError,
    PairingFingerprintMismatchError,
)
from app.api.plugins.rpi_cam.models import ConnectionMode
from app.api.plugins.rpi_cam.schemas import CameraCreate, CameraReadWithCredentials
from app.api.plugins.rpi_cam.schemas.pairing import (
    PairingClaimRequest,
    PairingPollResponse,
    PairingRegisterRequest,
    PairingRegisterResponse,
)
from app.api.plugins.rpi_cam.utils.encryption import decrypt_str
from app.core.config import settings as core_settings
from app.core.redis import RedisDep, delete_redis_key, get_redis_value, set_redis_value

logger = logging.getLogger(__name__)

router = PublicAPIRouter(prefix="/plugins/rpi-cam/pairing", tags=["RPi Camera Pairing"])

PAIRING_KEY_PREFIX = "rpi_cam:pairing"
PAIRING_TTL_SECONDS = 600  # 10 minutes for initial registration
PAIRING_CREDENTIAL_TTL_SECONDS = 300  # 5 minutes for RPi to pick up credentials

REGISTER_RATE_LIMIT = "10/minute"
POLL_RATE_LIMIT = "20/minute"

# Redis status values
_STATUS_WAITING = "waiting"
_STATUS_PAIRED = "paired"


def _pairing_key(code: str) -> str:
    return f"{PAIRING_KEY_PREFIX}:{code}"


def _build_ws_url() -> str:
    """Derive the WebSocket relay URL from the backend's configured API URL."""
    base = str(core_settings.backend_api_url).rstrip("/")
    ws_base = base.replace("https://", "wss://").replace("http://", "ws://")
    return f"{ws_base}/plugins/rpi-cam/ws/connect"


@router.post(
    "/register",
    response_model=PairingRegisterResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Register a pairing code (called by RPi)",
)
@limiter.limit(REGISTER_RATE_LIMIT)
async def register_pairing_code(
    request: Request,  # noqa: ARG001 — required by slowapi limiter
    body: PairingRegisterRequest,
    redis: RedisDep,
) -> PairingRegisterResponse:
    """Register a short-lived pairing code generated by an RPi camera.

    This endpoint is unauthenticated — the RPi has no credentials yet.
    Rate-limited to prevent abuse.
    """
    key = _pairing_key(body.code)

    # Check for collision
    existing = await get_redis_value(redis, key)
    if existing is not None:
        raise PairingCodeCollisionError

    payload = json.dumps({
        "rpi_fingerprint": body.rpi_fingerprint,
        "status": _STATUS_WAITING,
    })
    stored = await set_redis_value(redis, key, payload, ex=PAIRING_TTL_SECONDS)
    if not stored:
        msg = "Failed to store pairing code in Redis."
        raise RuntimeError(msg)

    logger.info("Pairing code %s registered.", body.code)
    return PairingRegisterResponse(code=body.code, expires_in=PAIRING_TTL_SECONDS)


@router.post(
    "/claim",
    response_model=CameraReadWithCredentials,
    summary="Claim a pairing code and create a camera (called by user)",
)
async def claim_pairing_code(
    body: PairingClaimRequest,
    session: AsyncSessionDep,
    current_user: CurrentActiveUserDep,
    redis: RedisDep,
) -> CameraReadWithCredentials:
    """Claim a pairing code: creates the camera and stores credentials for the RPi to retrieve."""
    key = _pairing_key(body.code)
    raw = await get_redis_value(redis, key)
    if raw is None:
        raise PairingCodeNotFoundError

    data = json.loads(raw)
    if data.get("status") != _STATUS_WAITING:
        raise PairingCodeAlreadyClaimedError

    # Create the camera
    camera_create = CameraCreate(
        name=body.camera_name,
        description=body.description,
        connection_mode=ConnectionMode.WEBSOCKET,
        auth_headers=None,
    )
    db_camera = await crud.create_camera(session, camera_create, current_user.id)
    api_key = decrypt_str(db_camera.encrypted_api_key)
    ws_url = _build_ws_url()

    # Store credentials for the RPi to pick up
    paired_payload = json.dumps({
        "status": _STATUS_PAIRED,
        "camera_id": str(db_camera.id),
        "api_key": api_key,
        "ws_url": ws_url,
    })
    await set_redis_value(redis, key, paired_payload, ex=PAIRING_CREDENTIAL_TTL_SECONDS)

    logger.info("Pairing code %s claimed by user %s, camera %s.", body.code, current_user.id, db_camera.id)
    return CameraReadWithCredentials.from_db_model_with_credentials(db_camera)


@router.get(
    "/poll",
    response_model=PairingPollResponse,
    summary="Poll pairing status (called by RPi)",
)
@limiter.limit(POLL_RATE_LIMIT)
async def poll_pairing_status(
    request: Request,  # noqa: ARG001 — required by slowapi limiter
    redis: RedisDep,
    code: str = Query(min_length=6, max_length=6, pattern=r"^[A-Z0-9]{6}$"),
    fingerprint: str = Query(min_length=8, max_length=64),
) -> PairingPollResponse:
    """Poll for pairing completion. Returns credentials once the user claims the code.

    Unauthenticated but requires the fingerprint nonce to prevent code-guessing attacks.
    """
    key = _pairing_key(code)
    raw = await get_redis_value(redis, key)
    if raw is None:
        raise PairingCodeNotFoundError

    data = json.loads(raw)

    if data.get("status") == _STATUS_WAITING:
        if data.get("rpi_fingerprint") != fingerprint:
            raise PairingFingerprintMismatchError
        return PairingPollResponse(status=_STATUS_WAITING)

    if data.get("status") == _STATUS_PAIRED:
        await delete_redis_key(redis, key)
        logger.info("Pairing credentials retrieved for code %s.", code)
        return PairingPollResponse(
            status=_STATUS_PAIRED,
            camera_id=data["camera_id"],
            api_key=data["api_key"],
            ws_url=data["ws_url"],
        )

    raise PairingCodeNotFoundError
