version: "0.2"
dictionaries:
  - coding-terms
  - cpp-compound-words
  - data-science
  - docker
  - en-gb
  - en-us
  - filetypes
  - fullstack
  - npm
  - python
  - python-common
  - software-tools
enabled: true
enabledFileTypes:
  "*": true
useGitignore: true
ignorePaths:
  - .devcontainer
  - .dockerignore
  - .git
  - .gitignore
  - .vscode
  - package-lock.json
  - pnpm-lock.yaml
  - uv.lock
  - "backend/app/api/auth/resources/disposable_email_domains.txt"
  - "frontend-app/src/assets/data/**"
  - "frontend-app/src/types/api.generated.ts"
language: en_us,nl
words:
  - anchore
  - aquasecurity
  - categorymateriallink
  - categoryproducttypelink
  - circularityproperties
  - crowdsource
  - dismissable
  - Donati
  - ERD
  - fileparenttype
  - GOMAXPROCS
  - imageparenttype
  - instrumentor
  - instrumentors
  - jaegertracing
  - Lierde
  - materialproductlink
  - newslettersubscriber
  - orcid
  - organizationrole
  - oauthaccount
  - physicalproperties
  - pressable
  - pressables
  - primaryjoin
  - producttype
  - refurbishers
  - relab
  - remanufacturability
  - remanufacturable
  - repairability
  - refetches
  - selectinload
  - shellcheck
  - subcomponent
  - subcomponents
  - subrepo
  - subrepos
  - supercategory
  - taxonomydomain
  - tsquery
  - tsvector
  - trixie
  - UNEP
  - viewability
  - zenodo

  # Temp (added to cSpell repo, should be available in the next cSpell release)
  - ASGI
  - Caddyfile
  - cloudflared
  - Fernet
  - fontawesome
  - justfile
  - mdformat
  - mjml
  - mypi
  - rclone
  - rhysd
  - Zensical

ignoreWords:
  - Jldmlldw
  - ellipsize
  - hibp
  - htmlcov
  - nosniff
  - otelcol
  - otlphttp
  - piexif
  - PYTHONDONTWRITEBYTECODE
  - PYTHONUNBUFFERED
  - USEPOLLING
  - uninstrument
  - worklets
  - xdist
  - zxcvbn
