# docker-compose.prod.yml (PRODUCTION - must be explicitly specified)
name: relab_prod # Separate prod containers, networks, and volumes from dev

services:
  cloudflared: # Cloudflared tunnel to cml-relab.org
    image: cloudflare/cloudflared:latest@sha256:4604b477520dc8322af5427da68b44f0bf814938e9d2e4814f2249ee4b03ffdf
    pull_policy: always
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file: .env
    volumes:
      - cloudflared_logs:/var/log/cloudflared

  database_backups: # Automated database backups to local file system
    image: prodrigestivill/postgres-backup-local:18
    restart: always
    volumes:
      - /var/opt/pgbackups:/backups
    depends_on:
      - database
    env_file: ./backend/.env
    # Ensure the container has permission to write to the mounted volume.
    # See also https://github.com/prodrigestivill/docker-postgres-backup-local?tab=readme-ov-file#usage
    user: postgres:postgres
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - SCHEDULE=@daily
      - TZ=UTC
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6

  backend:
    environment:
      # The public URL of the frontend, used for email generation and cookie management
      FRONTEND_URL: https://cml-relab.org

  docs:
    # Disable live reload for production
    command: ["serve", "--dev-addr=0.0.0.0:8000", "--no-livereload"]

volumes:
  cloudflared_logs:
