# docker-compose.prod.yml (PRODUCTION - must be explicitly specified)
name: relab_prod # Separate prod containers, networks, and volumes from dev

services:
  # Cloudflared tunnel to cml-relab.org
  cloudflared:
    image: cloudflare/cloudflared:latest
    pull_policy: always
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file: .env
    volumes:
      - cloudflared_logs:/var/log/cloudflared

  backend:
    environment:
      # The public URL of the frontend, used for email generation and cookie management
      FRONTEND_URL: https://cml-relab.org

  docs:
    # Disable live reload for production
    command: ["serve", "--dev-addr=0.0.0.0:8000", "--no-livereload"]

volumes:
  cloudflared_logs:
