# docker-compose.prod.yml (PRODUCTION - must be explicitly specified)
services:
  cloudflared: # Cloudflared tunnel to cml-relab.org
    image: cloudflare/cloudflared:latest
    pull_policy: always
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file: ./.env
    depends_on:
      - expo
      - fastapi
      - mkdocs
    volumes:
      - cloudflared_logs:/var/log/cloudflared

  expo:
    # Override for production
    command: sh -c "npx expo export -p web -c && npx serve dist -l 3000" 

  fastapi:
    environment:
      FRONTEND_URL: https://cml-relab.org # The public URL of the frontend, used for email generation by the FastAPI backend

volumes:
  cloudflared_logs:
