# docker-compose.override.yml (DEVELOPMENT - automatically used with docker-compose up)
name: relab_dev # Separate dev containers, networks, and volumes from prod

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/opt/relab/frontend # Mount source code for hot reload
      - /opt/relab/frontend/node_modules # Prevent overwriting node_modules
    ports:
      - "8010:8081"

  backend:
    build:
      dockerfile: Dockerfile.dev
    environment:
      FRONTEND_URL: http://localhost:8010
    volumes:
      - ./backend:/opt/relab/backend # Mount source code for hot reload
      - /opt/relab/backend/.venv # Prevent overwriting the virtual environment
    ports:
      - "8011:8000"

  docs:
    ports:
      - "8012:8000"

  database:
    ports:
      - "5433:5432"
