# docker-compose.prod.yml (PRODUCTION - must be explicitly specified)
services:
  cloudflared: # Cloudflared tunnel to cml-relab.org
    image: cloudflare/cloudflared:latest@sha256:4604b477520dc8322af5427da68b44f0bf814938e9d2e4814f2249ee4b03ffdf
    pull_policy: always
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file: ./.env
    depends_on:
      - expo
      - fastapi
      - mkdocs
    volumes:
      - cloudflared_logs:/var/log/cloudflared

  expo:
    command: sh -c "npx expo export -p web -c && npx serve dist -l 3000" # Override for production

  fastapi:
    environment:
      FRONTEND_URL: https://cml-relab.org # The public URL of the frontend, used for email generation by the FastAPI backend

volumes:
  cloudflared_logs:
