# OpenTelemetry Collector configuration for Jaeger tracing
# spell-checker: ignore otlphttp
file_format: yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:


exporters:
  debug:
    verbosity: normal
  otlphttp/jaeger:
    endpoint: http://jaeger:4318

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, otlphttp/jaeger ]
