FROM alpine:latest@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c69fc0d80990c2ad8dd412

# Build arguments
ARG WORKDIR=/opt/relab/backend_backups
ARG BACKUP_SCRIPT_NAME=backup_user_uploads.sh

# Install GNU tar and zstd for faster compression
RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
    apk -U upgrade && apk add --no-interactive\
    tar \
    zstd

WORKDIR $WORKDIR

# Set BACKUP_SCRIPT variable for entrypoint script
ENV BACKUP_SCRIPT=$WORKDIR/$BACKUP_SCRIPT_NAME

# Copy backup script
COPY scripts/backup/$BACKUP_SCRIPT_NAME .
RUN chmod +x ./$BACKUP_SCRIPT_NAME

# Copy entrypoint script
COPY scripts/backup/user_upload_backups_entrypoint.sh .
RUN chmod +x ./user_upload_backups_entrypoint.sh

ENTRYPOINT ["./user_upload_backups_entrypoint.sh"]
