FROM alpine:latest@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

# Build arguments
ARG WORKDIR=/opt/relab/backend_backups
ARG BACKUP_SCRIPT_NAME=backup_user_uploads.sh

# Install GNU tar and zstd for faster compression
RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
    apk -U upgrade && apk add --no-interactive\
    tar \
    zstd

WORKDIR $WORKDIR

# Set BACKUP_SCRIPT variable for entrypoint script
ENV BACKUP_SCRIPT=$WORKDIR/$BACKUP_SCRIPT_NAME

# Copy backup script
COPY scripts/backup/$BACKUP_SCRIPT_NAME .
RUN chmod +x ./$BACKUP_SCRIPT_NAME

# Copy entrypoint script
COPY scripts/backup/user_upload_backups_entrypoint.sh .
RUN chmod +x ./user_upload_backups_entrypoint.sh

ENTRYPOINT ["./user_upload_backups_entrypoint.sh"]
