"""Pydantic models for the RPi camera pairing flow."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class PairingRegisterRequest(BaseModel):
    """RPi → backend: register a pairing code."""

    code: str = Field(
        min_length=6,
        max_length=6,
        pattern=r"^[A-Z0-9]{6}$",
        description="6-character uppercase alphanumeric pairing code generated by the RPi.",
    )
    rpi_fingerprint: str = Field(
        min_length=8,
        max_length=64,
        description="Random nonce generated by the RPi. Required to retrieve credentials later.",
    )


class PairingRegisterResponse(BaseModel):
    """Backend → RPi: confirmation of registered pairing code."""

    code: str
    expires_in: int = Field(description="Seconds until the pairing code expires.")


class PairingClaimRequest(BaseModel):
    """User → backend: claim a pairing code and create a camera."""

    code: str = Field(
        min_length=6,
        max_length=6,
        pattern=r"^[A-Z0-9]{6}$",
        description="Pairing code displayed on the RPi's setup page.",
    )
    camera_name: str = Field(min_length=2, max_length=100, description="Name for the new camera.")
    description: str | None = Field(default=None, max_length=500)


class PairingPollResponse(BaseModel):
    """Backend → RPi: current pairing status."""

    status: Literal["waiting", "paired"]
    camera_id: str | None = None
    api_key: str | None = None
    ws_url: str | None = None
