"""Pydantic models for the RPi camera pairing flow."""

from pydantic import BaseModel, Field
from relab_rpi_cam_models import PairingCode

from app.api.common.validation import MultilineUserText, SingleLineUserText


class PairingClaimRequest(BaseModel):
    """User -> backend: claim a pairing code and create a camera."""

    code: PairingCode = Field(description="Pairing code displayed on the RPi's setup page.")
    camera_name: SingleLineUserText = Field(min_length=2, max_length=100, description="Name for the new camera.")
    description: MultilineUserText | None = Field(default=None, max_length=500)


class PairingPollRequest(BaseModel):
    """Pi -> backend: poll pairing status.

    Sent as a POST body (not query params) so the pairing code and device
    fingerprint never land in reverse-proxy or uvicorn access logs.
    """

    code: PairingCode = Field(description="Pairing code generated by the Pi.")
    fingerprint: str = Field(
        min_length=8,
        max_length=64,
        description="Random device fingerprint nonce chosen at registration.",
    )
