"""Pydantic models for the RPi camera pairing flow."""

import re

from pydantic import BaseModel, Field
from relab_rpi_cam_models import PairingCode

from app.api.common.validation import MultilineUserText, SingleLineUserText

# ASCII only: a non-ASCII fingerprint makes hmac.compare_digest raise TypeError, an
# unauthenticated 500. The Pi generates `secrets.token_urlsafe(16)`, which fits.
# NOTE: belongs on the fingerprint fields in relab-rpi-cam-models; until it moves
# upstream the register route re-checks it by hand.
FINGERPRINT_PATTERN = re.compile(r"^[A-Za-z0-9._~-]{8,64}$")


class PairingClaimRequest(BaseModel):
    """User -> backend: claim a pairing code and create a camera."""

    code: PairingCode = Field(description="Pairing code displayed on the RPi's setup page.")
    camera_name: SingleLineUserText = Field(min_length=2, max_length=100, description="Name for the new camera.")
    description: MultilineUserText | None = Field(default=None, max_length=500)


class PairingPollRequest(BaseModel):
    """Pi -> backend: poll pairing status.

    Sent as a POST body (not query params) so the pairing code and device
    fingerprint never land in reverse-proxy or uvicorn access logs.
    """

    code: PairingCode = Field(description="Pairing code generated by the Pi.")
    fingerprint: str = Field(
        min_length=8,
        max_length=64,
        pattern=FINGERPRINT_PATTERN.pattern,
        description="Random device fingerprint nonce chosen at registration.",
    )
