// Generated by scripts/sync_brand_assets.py from assets/tokens.json. Do not edit.
export const designTokens = {
  "radius": {
    "control": 6,
    "card": 8,
    "overlay": 12,
    "full": 9999
  },
  "shadowOverlay": {
    "light": "0 8px 24px rgba(20, 40, 80, 0.16)",
    "dark": "0 8px 24px rgba(0, 0, 0, 0.55)"
  },
  "scrim": {
    "light": "rgba(12, 18, 32, 0.50)",
    "dark": "rgba(0, 0, 0, 0.55)"
  },
  "type": {
    "display": {
      "size": 38,
      "line": 44
    },
    "title": {
      "size": 24,
      "line": 30
    },
    "body": {
      "size": 16,
      "line": 26
    },
    "label": {
      "size": 13,
      "line": 18,
      "trackingEm": 0.1
    },
    "data": {
      "size": 14,
      "line": 20
    }
  },
  "chart": {
    "blue": {
      "fill": "#E3ECFA",
      "stroke": "#1F4C96",
      "text": "#143567"
    },
    "manila": {
      "fill": "#F7ECD4",
      "stroke": "#8F6212",
      "text": "#5C3F0A"
    },
    "verdigris": {
      "fill": "#E0F2ED",
      "stroke": "#0E6B5E",
      "text": "#0A4F45"
    },
    "copper": {
      "fill": "#F9E7DE",
      "stroke": "#A8542F",
      "text": "#6E371F"
    },
    "violet": {
      "fill": "#EDE6F7",
      "stroke": "#6D4FA3",
      "text": "#44337A"
    },
    "rose": {
      "fill": "#FAE4EC",
      "stroke": "#B0316E",
      "text": "#6E2048"
    },
    "slate": {
      "fill": "#F1F4F8",
      "stroke": "#5A6675",
      "text": "#16202E"
    }
  }
} as const;
