"""Public user management routes."""

from __future__ import annotations

from typing import Annotated
from uuid import UUID

from fastapi import HTTPException, Response, Security
from sqlalchemy import select

from app.api.auth.dependencies import (
    current_active_user,
    optional_current_active_user,
)
from app.api.auth.models import User
from app.api.auth.schemas import (
    PublicProfileView,
    UserRead,
    UserUpdate,
)
from app.api.auth.services.privacy import can_view_profile
from app.api.auth.services.stats import get_profile_stats, recompute_user_profile_stats
from app.api.auth.services.user_manager import fastapi_user_manager
from app.api.common.routers.dependencies import AsyncSessionDep
from app.api.common.routers.openapi import PublicAPIRouter

### User self-management routes ###

router = PublicAPIRouter(prefix="/users", tags=["users"], dependencies=[Security(current_active_user)])

# Include autogenerated user management routes (for self-management)
router.include_router(
    fastapi_user_manager.get_users_router(UserRead, UserUpdate),
)


## Public Profile Routes ##

public_user_router = PublicAPIRouter(prefix="/users", tags=["users"])


@public_user_router.get(
    "/{identifier}/profile",
    response_model=PublicProfileView,
    summary="Get public profile of a user",
)
async def get_public_profile(
    identifier: str,
    response: Response,
    session: AsyncSessionDep,
    current_user: Annotated[User | None, Security(optional_current_active_user)],
) -> PublicProfileView:
    """Get public profile statistics for a specified user by their username or UUID.

    Returns 404 if the user is not found or if the profile is marked as private (and you are not the user).
    Includes lazy initialization of stats if they are missing.
    """
    # Response is viewer-dependent (visibility rules change with auth state),
    # so browsers and intermediaries must revalidate on every request.
    response.headers["Cache-Control"] = "private, no-store"

    # 1. Look up user by UUID or Username
    user = None
    try:
        # Check if identifier is a valid UUID
        user_uuid = UUID(identifier)
        user = await session.get(User, user_uuid)
    except ValueError, AttributeError:
        # Not a valid UUID, search by username
        stmt = select(User).where(User.username == identifier)
        result = await session.execute(stmt)
        user = result.unique().scalar_one_or_none()

    if not user:
        raise HTTPException(status_code=404, detail="Profile not found")

    # 2. Check privacy settings
    if not can_view_profile(user, current_user):
        raise HTTPException(status_code=404, detail="Profile not found")

    # 3. Lazy initialization of stats if no full snapshot exists yet
    if user.profile_stats_computed_at is None or not user.profile_stats:
        stats = await recompute_user_profile_stats(session, user.id)
        await session.commit()
    else:
        stats = get_profile_stats(user)

    return PublicProfileView.from_profile_stats(
        username=user.username,
        created_at=user.created_at,
        stats=stats,
    )
