"""Public user management routes."""

from __future__ import annotations

from typing import Annotated, cast
from uuid import UUID

from fastapi import HTTPException, Security
from fastapi_pagination import Page
from sqlalchemy import select

from app.api.auth.crud.organizations import (
    delete_organization_as_owner,
    update_user_organization,
)
from app.api.auth.crud.organizations import (
    get_organization_members as get_org_members,
)
from app.api.auth.crud.organizations import (
    leave_organization as leave_org,
)
from app.api.auth.dependencies import (
    CurrentActiveVerifiedUserDep,
    CurrentUserOrgDep,
    CurrentUserOwnedOrgDep,
    current_active_user,
    optional_current_active_user,
)
from app.api.auth.models import Organization, User
from app.api.auth.schemas import (
    OrganizationRead,
    OrganizationReadPublic,
    OrganizationUpdate,
    PublicProfileView,
    UserRead,
    UserReadPublic,
    UserUpdate,
)
from app.api.auth.services.privacy import (
    VISIBILITY_COMMUNITY,
    VISIBILITY_PRIVATE,
    VISIBILITY_PUBLIC,
)
from app.api.auth.services.profile_cache import (
    cache_public_profile,
    get_cached_public_profile,
)
from app.api.auth.services.stats import recompute_user_stats
from app.api.auth.services.user_manager import fastapi_user_manager
from app.api.common.routers.dependencies import AsyncSessionDep
from app.api.common.routers.openapi import PublicAPIRouter

### User self-management routes ###

router = PublicAPIRouter(prefix="/users", tags=["users"], dependencies=[Security(current_active_user)])

# Include autogenerated user management routes (for self-management)
router.include_router(
    fastapi_user_manager.get_users_router(UserRead, UserUpdate),
)


## User organization routes ##
@router.get(
    "/me/organization", response_model=OrganizationReadPublic, summary="Get the organization of the current user"
)
async def get_user_organization(current_user_organization: CurrentUserOrgDep) -> Organization:
    """Get the organization of the current user."""
    return current_user_organization


@router.get(
    "/me/organization/members",
    response_model=Page[UserReadPublic],
    summary="Get the members of the organization of the current user",
)
async def get_user_organization_members(
    current_user_organization: CurrentUserOrgDep,
    current_user: CurrentActiveVerifiedUserDep,
    session: AsyncSessionDep,
) -> Page[UserReadPublic]:
    """Get the members of the organization of the current user."""
    return cast(
        "Page[UserReadPublic]",
        await get_org_members(
            session,
            current_user_organization.id,
            current_user,
            paginate=True,
            read_schema=UserReadPublic,
        ),
    )


@router.patch("/me/organization", response_model=OrganizationRead, summary="Update your organization")
async def update_organization(
    db_organization: CurrentUserOwnedOrgDep,
    organization_in: OrganizationUpdate,
    session: AsyncSessionDep,
) -> Organization:
    """Update organization as owner."""
    return await update_user_organization(session, db_organization, organization_in)


@router.delete("/me/organization", status_code=204, summary="Delete your organization as owner")
async def delete_my_organization(
    session: AsyncSessionDep,
    current_user: CurrentActiveVerifiedUserDep,
) -> None:
    """Delete organization as owner. Fails if organization has members."""
    return await delete_organization_as_owner(session, current_user)


@router.delete("/me/organization/membership", status_code=204, summary="Leave current organization")
async def leave_organization(
    session: AsyncSessionDep,
    current_user: CurrentActiveVerifiedUserDep,
) -> None:
    """Leave current organization. Cannot be used by organization owner."""
    await leave_org(session, current_user)


## Public Profile Routes ##

public_user_router = PublicAPIRouter(prefix="/users", tags=["users"])


@public_user_router.get(
    "/{identifier}/profile",
    response_model=PublicProfileView,
    summary="Get public profile of a user",
)
async def get_public_profile(
    identifier: str,
    session: AsyncSessionDep,
    current_user: Annotated[User | None, Security(optional_current_active_user)],
) -> PublicProfileView:
    """Get public profile statistics for a specified user by their username or UUID.

    Returns 404 if the user is not found or if the profile is marked as private (and you are not the user).
    Includes lazy initialization of stats if they are missing.
    """
    # 1. Look up user by UUID or Username
    user = None
    try:
        # Check if identifier is a valid UUID
        user_uuid = UUID(identifier)
        user = await session.get(User, user_uuid)
    except ValueError, AttributeError:
        # Not a valid UUID, search by username
        stmt = select(User).where(User.username == identifier)
        result = await session.execute(stmt)
        user = result.unique().scalar_one_or_none()

    if not user:
        raise HTTPException(status_code=404, detail="Profile not found")

    # 2. Check privacy settings
    profile_visibility = user.preferences.get("profile_visibility", VISIBILITY_PUBLIC)

    if profile_visibility == VISIBILITY_PRIVATE:
        is_self = current_user and current_user.id == user.id
        is_admin = current_user and current_user.is_superuser
        if not (is_self or is_admin):
            raise HTTPException(status_code=404, detail="Profile not found")

    elif profile_visibility == VISIBILITY_COMMUNITY:
        if not current_user:
            raise HTTPException(status_code=404, detail="Profile not found")

    cached_profile = await get_cached_public_profile(user.id)
    if cached_profile is not None:
        return cached_profile

    # 3. Lazy initialization of stats if cache is empty
    stats = user.stats_cache
    if not stats:
        # Recompute on the fly and save to user
        stats = await recompute_user_stats(session, user.id)
        await session.commit()

    profile = PublicProfileView(
        username=user.username,
        created_at=user.created_at,
        product_count=stats.get("product_count", 0),
        total_weight_kg=stats.get("total_weight_kg", 0.0),
        image_count=stats.get("image_count", 0),
        top_category=stats.get("top_category", "None"),
    )
    await cache_public_profile(user.id, profile)
    return profile
