"""Public user management routes."""

from __future__ import annotations

from typing import cast

from fastapi import Security
from fastapi_pagination import Page

from app.api.auth import crud
from app.api.auth.dependencies import (
    CurrentActiveVerifiedUserDep,
    CurrentUserOrgDep,
    CurrentUserOwnedOrgDep,
    current_active_user,
)
from app.api.auth.models import Organization
from app.api.auth.schemas import (
    OrganizationRead,
    OrganizationReadPublic,
    OrganizationUpdate,
    UserRead,
    UserReadPublic,
    UserUpdate,
)
from app.api.auth.services.user_manager import fastapi_user_manager
from app.api.common.routers.dependencies import AsyncSessionDep
from app.api.common.routers.openapi import PublicAPIRouter

### User self-management routes ###

router = PublicAPIRouter(prefix="/users", tags=["users"], dependencies=[Security(current_active_user)])

# Include autogenerated user management routes (for self-management)
router.include_router(
    fastapi_user_manager.get_users_router(UserRead, UserUpdate),
)


## User organization routes ##
@router.get(
    "/me/organization", response_model=OrganizationReadPublic, summary="Get the organization of the current user"
)
async def get_user_organization(current_user_organization: CurrentUserOrgDep) -> Organization:
    """Get the organization of the current user."""
    return current_user_organization


@router.get(
    "/me/organization/members",
    response_model=Page[UserReadPublic],
    summary="Get the members of the organization of the current user",
)
async def get_user_organization_members(
    current_user_organization: CurrentUserOrgDep,
    current_user: CurrentActiveVerifiedUserDep,
    session: AsyncSessionDep,
) -> Page[UserReadPublic]:
    """Get the members of the organization of the current user."""
    return cast(
        "Page[UserReadPublic]",
        await crud.get_organization_members(
            session,
            current_user_organization.id,
            current_user,
            paginate=True,
            read_schema=UserReadPublic,
        ),
    )


@router.patch("/me/organization", response_model=OrganizationRead, summary="Update your organization")
async def update_organization(
    db_organization: CurrentUserOwnedOrgDep,
    organization_in: OrganizationUpdate,
    session: AsyncSessionDep,
) -> Organization:
    """Update organization as owner."""
    return await crud.update_user_organization(session, db_organization, organization_in)


@router.delete("/me/organization", status_code=204, summary="Delete your organization as owner")
async def delete_my_organization(
    session: AsyncSessionDep,
    current_user: CurrentActiveVerifiedUserDep,
) -> None:
    """Delete organization as owner. Fails if organization has members."""
    return await crud.delete_organization_as_owner(session, current_user)


@router.delete("/me/organization/membership", status_code=204, summary="Leave current organization")
async def leave_organization(
    session: AsyncSessionDep,
    current_user: CurrentActiveVerifiedUserDep,
) -> None:
    """Leave current organization. Cannot be used by organization owner."""
    await crud.leave_organization(session, current_user)
