"""add foreign keys for organization and user

Revision ID: 07d992454431
Revises: 33b00b31e537
Create Date: 2025-06-30 00:05:57.146331

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

import app.api.common.models.custom_types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07d992454431"
down_revision: str | None = "33b00b31e537"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("fk_organization_owner", "organization", "user", ["owner_id"], ["id"], use_alter=True)
    op.create_foreign_key("fk_user_organization", "user", "organization", ["organization_id"], ["id"], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_organization", "user", type_="foreignkey")
    op.drop_constraint("fk_organization_owner", "organization", type_="foreignkey")
    # ### end Alembic commands ###
