"""Move from weight_kg to weight_g

Revision ID: 0faa2fa19f62
Revises: b43d157d07f1
Create Date: 2025-11-17 14:52:08.201228

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

import app.api.common.models.custom_types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0faa2fa19f62"
down_revision: str | None = "b43d157d07f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("physicalproperties", sa.Column("weight_g", sa.Float(), nullable=True))

    # Migrate data: convert kg to g (multiply by 1000)
    op.execute("""
        UPDATE physicalproperties
        SET weight_g = weight_kg * 1000
        WHERE weight_kg IS NOT NULL
    """)

    op.drop_column("physicalproperties", "weight_kg")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "physicalproperties",
        sa.Column("weight_kg", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )

    # Migrate data back: convert g to kg (divide by 1000)
    op.execute("""
        UPDATE physicalproperties
        SET weight_kg = weight_g / 1000
        WHERE weight_g IS NOT NULL
    """)

    op.drop_column("physicalproperties", "weight_g")
    # ### end Alembic commands ###
