"""remove product dismantling notes

Revision ID: 244aa961ea6e
Revises: 1f7e8a2b4c6d
Create Date: 2026-04-28 17:26:21.960294

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "244aa961ea6e"
down_revision: str | None = "1f7e8a2b4c6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "dismantling_notes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("dismantling_notes", sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
