"""Add last_login tracking fields to user model

Revision ID: 4c248b3004c6
Revises: 84d2f72dccc7
Create Date: 2026-02-17 16:41:13.956150

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c248b3004c6"
down_revision: str | None = "84d2f72dccc7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("last_login_at", sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column("user", sa.Column("last_login_ip", sa.String(45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_login_ip")
    op.drop_column("user", "last_login_at")
    # ### end Alembic commands ###
