"""add_user_stats_cache

Revision ID: 4d379aaa416a
Revises: 6891389e6660
Create Date: 2026-04-14 12:01:46.778801

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4d379aaa416a"
down_revision: str | None = "6891389e6660"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("stats_cache", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "stats_cache")
    # ### end Alembic commands ###
