"""add has_usable_password to user

Revision ID: 5bfb8deb5fa6
Revises: a5059204b5c6
Create Date: 2026-07-10 22:14:13.407702

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5bfb8deb5fa6"
down_revision: str | None = "a5059204b5c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("user", sa.Column("has_usable_password", sa.Boolean(), server_default="true", nullable=False))
    # Backfill: any account with a linked OAuth login might be OAuth-only (we can't tell
    # a set password from the random one fastapi-users assigns). Default those to False so
    # an OAuth-only user is never asked for a password they never set when unlinking; a
    # password-set (reset/change) flips it back to True. Password-only accounts keep True.
    op.execute('UPDATE "user" SET has_usable_password = false WHERE id IN (SELECT DISTINCT user_id FROM oauthaccount)')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "has_usable_password")
    # ### end Alembic commands ###
