"""Increase string fields max length

Revision ID: 65da9d7e309c
Revises: 07d992454431
Create Date: 2025-10-05 20:54:07.828158

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

import app.api.common.models.custom_types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65da9d7e309c"
down_revision: str | None = "07d992454431"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "camera",
        "name",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "material",
        "name",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "material",
        "source",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "organization",
        "name",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "organization",
        "location",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "product",
        "name",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "producttype",
        "name",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "taxonomy",
        "name",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "taxonomy",
        "source",
        existing_type=sa.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(length=500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "taxonomy",
        "source",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "taxonomy",
        "name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "producttype",
        "name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "product",
        "name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "organization",
        "location",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "organization",
        "name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "material",
        "source",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "material",
        "name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "camera",
        "name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
