"""Remove relay_last_seen_at from Camera

Revision ID: 6891389e6660
Revises: d9ffb53c12c0
Create Date: 2026-04-13 18:26:16.817503

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6891389e6660"
down_revision: str | None = "d9ffb53c12c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("camera", "relay_last_seen_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "camera",
        sa.Column("relay_last_seen_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
