"""Add websocket connection to RPI-cams

Revision ID: 70e78d937e0b
Revises: a1b2c3d4e5f6
Create Date: 2026-04-07 15:14:18.076123

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

import app.api.common.models.custom_types

# revision identifiers, used by Alembic.
revision: str = "70e78d937e0b"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("HTTP", "WEBSOCKET", name="connectionmode").create(op.get_bind())
    op.add_column(
        "camera",
        sa.Column(
            "connection_mode",
            postgresql.ENUM("HTTP", "WEBSOCKET", name="connectionmode", create_type=False),
            server_default="HTTP",
            nullable=False,
        ),
    )
    op.alter_column("camera", "url", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("camera", "url", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("camera", "connection_mode")
    sa.Enum("HTTP", "WEBSOCKET", name="connectionmode").drop(op.get_bind())
    # ### end Alembic commands ###
