"""Simplify Circularity_properties model

Revision ID: 84d2f72dccc7
Revises: 0faa2fa19f62
Create Date: 2025-11-27 12:01:32.413795

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

import app.api.common.models.custom_types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84d2f72dccc7"
down_revision: str | None = "0faa2fa19f62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "circularityproperties", "recyclability_observation", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column(
        "circularityproperties", "repairability_observation", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column(
        "circularityproperties", "remanufacturability_observation", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "circularityproperties", "remanufacturability_observation", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.alter_column(
        "circularityproperties", "repairability_observation", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.alter_column(
        "circularityproperties", "recyclability_observation", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    # ### end Alembic commands ###
