"""Add version to taxonomy model

Revision ID: 95cc94317b69
Revises: 65da9d7e309c
Create Date: 2025-10-12 16:23:32.824396

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

import app.api.common.models.custom_types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95cc94317b69"
down_revision: str | None = "65da9d7e309c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("taxonomy", sa.Column("version", sqlmodel.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("taxonomy", "version")
    # ### end Alembic commands ###
