"""Add is_profile_public to user

Revision ID: a1b2c3d4e5f6
Revises: 95cc94317b69
Create Date: 2025-11-18 18:00:00.000000

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: str | None = "95cc94317b69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_profile_public", sa.Boolean(), nullable=False, server_default=sa.text("true")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_profile_public")
    # ### end Alembic commands ###
