"""add mfa recovery codes

Revision ID: a5059204b5c6
Revises: 8b70d4c2f1a9
Create Date: 2026-07-07 15:32:39.238169

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a5059204b5c6"
down_revision: str | None = "8b70d4c2f1a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("mfa_recovery_codes", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "mfa_recovery_codes")
    # ### end Alembic commands ###
