"""Add thumbnail_path to image

Revision ID: a7f3d8e2c1b4
Revises: 95cc94317b69
Create Date: 2025-11-18 14:00:00.000000

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7f3d8e2c1b4"
down_revision: str | None = "95cc94317b69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("image", sa.Column("thumbnail_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("image", "thumbnail_path")
    # ### end Alembic commands ###
