"""Add basic circularity_properties model

Revision ID: b43d157d07f1
Revises: 95cc94317b69
Create Date: 2025-11-17 13:30:07.435637

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

import app.api.common.models.custom_types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b43d157d07f1"
down_revision: str | None = "95cc94317b69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "circularityproperties",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("recyclability_observation", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("recyclability_comment", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("recyclability_reference", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("repairability_observation", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("repairability_comment", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("repairability_reference", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("remanufacturability_observation", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("remanufacturability_comment", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("remanufacturability_reference", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("circularityproperties")
    # ### end Alembic commands ###
