"""add_oauth_account_uniqueness_constraint

Revision ID: da288fbcf15e
Revises: 4c248b3004c6
Create Date: 2026-03-17 14:22:56.702224

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da288fbcf15e"
down_revision: str | None = "4c248b3004c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_oauth_account_identity", "oauthaccount", ["oauth_name", "account_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_oauth_account_identity", "oauthaccount", type_="unique")
    # ### end Alembic commands ###
