"""Add user preferences

Revision ID: e3d54054d34a
Revises: 70e78d937e0b
Create Date: 2026-04-08 03:57:06.451232

"""
# spell-checker: ignore astext

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

import app.api.common.models.custom_types

# revision identifiers, used by Alembic.
revision: str = "e3d54054d34a"
down_revision: str | None = "70e78d937e0b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "preferences")
    # ### end Alembic commands ###
