"""remove organizations

Revision ID: eddf31f2e90c
Revises: f8a91c2d4e6b
Create Date: 2026-05-01 16:07:02.036175

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eddf31f2e90c"
down_revision: str | None = "f8a91c2d4e6b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_organization_name"), table_name="organization")
    op.drop_constraint(op.f("fk_user_organization"), "user", type_="foreignkey")
    op.drop_column("user", "organization_id")
    op.drop_column("user", "organization_role")
    op.drop_table("organization")
    sa.Enum("OWNER", "MEMBER", name="organizationrole").drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("OWNER", "MEMBER", name="organizationrole").create(op.get_bind())
    op.add_column(
        "user",
        sa.Column(
            "organization_role",
            postgresql.ENUM("OWNER", "MEMBER", name="organizationrole", create_type=False),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column("user", sa.Column("organization_id", sa.UUID(), autoincrement=False, nullable=True))
    op.create_table(
        "organization",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("location", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], name=op.f("fk_organization_owner")),
        sa.PrimaryKeyConstraint("id", name=op.f("organization_pkey")),
    )
    op.create_index(op.f("ix_organization_name"), "organization", ["name"], unique=True)
    op.create_foreign_key(op.f("fk_user_organization"), "user", "organization", ["organization_id"], ["id"])
    # ### end Alembic commands ###
