"""Export the generated data-model diagrams and dataset codebook for the docs site.

Two outputs, each with a single source:

* the ER diagrams, from the SQLAlchemy metadata — the tables, columns and foreign keys
  as they actually exist, so an added column cannot quietly go undocumented;
* the dataset codebook, from the release schemas in ``scripts.build_dataset_release`` —
  the columns a published release carries, with the descriptions declared alongside them.

Both are partials. The prose around them stays hand-written in the docs pages that import
them, so this script never has an opinion about wording.
"""

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

import pyarrow as pa
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.api.common.models.base import Base
from app.core.model_registry import load_models
from scripts.build_dataset_release import RELEASE_TABLES, field_description

if TYPE_CHECKING:
    from collections.abc import Iterator, Sequence

# Anchor outputs to the repo root (…/backend/scripts/generate/export_datamodel.py),
# not the CWD, so --check doesn't false-drift when run from outside backend/.
_REPO_ROOT = Path(__file__).resolve().parents[3]
PARTIALS_DIR = _REPO_ROOT / "docs" / "src" / "components" / "datamodel"

_BANNER = "{/* Generated by backend/scripts/generate/export_datamodel.py. Do not edit. */}"


### Module grouping ###
@dataclass(frozen=True)
class Module:
    """One bounded context, rendered as one ER diagram."""

    slug: str
    title: str
    package: str


# One entry per context that owns tables. A context with no entry raises rather than
# dropping its tables off the diagrams silently.
MODULES = (
    Module("user-management", "User management", "app.api.auth"),
    Module("reference-data", "Reference data", "app.api.reference_data"),
    Module("data-collection", "Data collection", "app.api.data_collection"),
    Module("file-storage", "File storage", "app.api.file_storage"),
    Module("camera-plugin", "Camera plugin", "app.api.plugins.rpi_cam"),
)


def _module_tables() -> dict[Module, list[sa.Table]]:
    """Group every mapped table under the module whose package declares it."""
    load_models()
    grouped: dict[Module, list[sa.Table]] = {module: [] for module in MODULES}
    for mapper in Base.registry.mappers:
        table = mapper.local_table
        owners = [module for module in MODULES if mapper.class_.__module__.startswith(f"{module.package}.")]
        if len(owners) != 1:
            msg = f"{table.name} is declared in {mapper.class_.__module__}, which matches {len(owners)} modules"
            raise RuntimeError(msg)
        grouped[owners[0]].append(table)
    return {module: sorted(tables, key=lambda table: table.name) for module, tables in grouped.items()}


### Column rendering ###
_PG = postgresql.dialect()

# Compiled Postgres spellings that are longer than they are clear in a diagram.
_TYPE_ALIASES = {
    "timestamp with time zone": "timestamptz",
    "double precision": "float",
    "character varying": "varchar",
}

_TIMESTAMP_COLUMNS = ("created_at", "updated_at")


def _type_name(type_: sa.types.TypeEngine) -> str:
    """Return a short, Mermaid-safe name for a column type."""
    if isinstance(type_, sa.ARRAY):
        return f"{_type_name(type_.item_type)}[]"
    if isinstance(type_, sa.Enum):
        return type_.name or "enum"
    compiled = type_.compile(_PG).split("(")[0].strip().lower()
    return _TYPE_ALIASES.get(compiled, compiled)


def _keys(column: sa.Column) -> str:
    """Return the Mermaid key markers for a column."""
    markers = []
    if column.primary_key:
        markers.append("PK")
    if column.foreign_keys:
        markers.append("FK")
    if column.unique:
        markers.append("UK")
    return ", ".join(markers)


def _comment(column: sa.Column) -> str:
    """Return the note shown beside a column: its docstring, else its enum values."""
    if column.doc:
        return column.doc
    type_ = column.type
    member_type = type_.item_type if isinstance(type_, sa.ARRAY) else type_
    if isinstance(member_type, sa.Enum):
        return ", ".join(member_type.enums)
    return ""


def _ordered_columns(table: sa.Table) -> list[sa.Column]:
    """Order columns for reading: identity, then links, then the rest, then timestamps.

    Declaration order is mixin order, which puts a table's own id halfway down its column
    list, so it is not worth preserving here.
    """

    def sort_key(column: sa.Column) -> tuple[int, str | int]:
        if column.primary_key:
            return (0, column.name)
        if column.name in _TIMESTAMP_COLUMNS:
            return (3, _TIMESTAMP_COLUMNS.index(column.name))
        if column.foreign_keys:
            return (1, column.name)
        return (2, column.name)

    return sorted(table.columns, key=sort_key)


### Relationships ###
@dataclass(frozen=True)
class Relation:
    """One parent-to-children edge in a diagram."""

    parent: str
    child: str
    label: str
    optional: bool
    polymorphic: bool = False


# Media tables point at their parent through a type discriminator and a bare id rather than
# a foreign key, so the edges come from the enum's members instead of the FK metadata.
_PARENT_TYPE_COLUMN = "parent_type"


def _foreign_key_relations(table: sa.Table) -> Iterator[Relation]:
    """Yield one relation per foreign key on *table*."""
    constraints = sorted(table.foreign_key_constraints, key=lambda c: sorted(column.name for column in c.columns))
    for constraint in constraints:
        columns = list(constraint.columns)
        parent = constraint.referred_table.name
        label = columns[0].name.removesuffix("_id").replace("_", " ") if len(columns) == 1 else parent
        yield Relation(parent, table.name, label, optional=any(column.nullable for column in columns))


def _polymorphic_relations(table: sa.Table, table_names: set[str]) -> Iterator[Relation]:
    """Yield the parent edges a media table declares through its parent_type enum."""
    column = table.columns.get(_PARENT_TYPE_COLUMN)
    if column is None or not isinstance(column.type, sa.Enum):
        return
    for member in column.type.enums:
        parent = member.lower().replace("_", "")
        if parent not in table_names:
            msg = f"{table.name}.{_PARENT_TYPE_COLUMN} names {member!r}, which matches no table"
            raise RuntimeError(msg)
        yield Relation(parent, table.name, "media parent", optional=False, polymorphic=True)


def _relations(tables: Sequence[sa.Table], table_names: set[str]) -> list[Relation]:
    """Return every relation whose child table sits in this module."""
    relations = []
    for table in tables:
        relations.extend(_foreign_key_relations(table))
        relations.extend(_polymorphic_relations(table, table_names))
    return relations


### Diagram rendering ###
def _acc_descr(module: Module, tables: Sequence[sa.Table], relations: Sequence[Relation]) -> str:
    """Describe the diagram for a screen reader.

    Generated rather than authored: mechanical phrasing that stays true beats better
    phrasing that silently stops matching the diagram it describes.
    """
    entities = ", ".join(table.name.upper() for table in tables)
    sentences = [f"The {module.title.lower()} tables are {entities}."]

    for relation in (r for r in relations if not r.polymorphic):
        quantifier = "zero or one" if relation.optional else "exactly one"
        sentences.append(
            f"Each {relation.child.upper()} row names {quantifier} {relation.parent.upper()} as its {relation.label}."
        )

    for table in tables:
        parents = [r.parent.upper() for r in relations if r.polymorphic and r.child == table.name]
        if parents:
            sentences.append(f"Each {table.name.upper()} row is attached to exactly one of {', '.join(parents)}.")

    if len(sentences) == 1:
        sentences.append("They have no relationships to each other.")
    return " ".join(sentences)


def _render_diagram(module: Module, tables: Sequence[sa.Table], table_names: set[str]) -> str:
    """Render one module's Mermaid ER diagram."""
    relations = _relations(tables, table_names)
    lines = [
        "erDiagram",
        f"    accTitle: {module.title} entities",
        f"    accDescr: {_acc_descr(module, tables, relations)}",
    ]

    for table in tables:
        lines.extend(["", f"    {table.name.upper()} {{"])
        for column in _ordered_columns(table):
            # Mermaid delimits the note with double quotes and offers no escape for one.
            comment = _comment(column).replace('"', "'")
            parts = [_type_name(column.type), column.name, _keys(column), f'"{comment}"' if comment else ""]
            lines.append(f"        {' '.join(part for part in parts if part)}")
        lines.append("    }")

    lines.append("")
    for relation in relations:
        cardinality = "|o" if relation.optional else "||"
        lines.append(f'    {relation.parent.upper()} {cardinality}--o{{ {relation.child.upper()} : "{relation.label}"')

    return "\n".join(lines)


def _render_diagram_partial(module: Module, tables: Sequence[sa.Table], table_names: set[str]) -> str:
    """Wrap a module's diagram in the MDX partial the docs page imports."""
    return f"{_BANNER}\n\n```mermaid\n{_render_diagram(module, tables, table_names)}\n```\n"


### Codebook rendering ###
_ARROW_TYPE_NAMES = {
    "int64": "integer",
    "double": "float",
    "bool": "boolean",
    "string": "text",
}


def _arrow_type_name(type_: pa.DataType) -> str:
    """Return a reader-facing name for a release column type."""
    if pa.types.is_list(type_):
        return f"list of {_arrow_type_name(type_.value_type)}"
    if pa.types.is_timestamp(type_):
        return "timestamp (UTC)"
    return _ARROW_TYPE_NAMES.get(str(type_), str(type_))


def _render_codebook() -> str:
    """Render the field-by-field table for every file in a dataset release."""
    lines = [_BANNER]
    for table in RELEASE_TABLES:
        lines.extend(
            [
                "",
                f"### `{table.path}`",
                "",
                table.description,
                "",
                "| Column | Type | Required | Description |",
                "| ------ | ---- | -------- | ----------- |",
            ]
        )
        for field in table.schema:
            description = field_description(field)
            if not description:
                msg = f"{table.path} column {field.name!r} has no description; add one in build_dataset_release.py"
                raise RuntimeError(msg)
            required = "no" if field.nullable else "yes"
            # A pipe would end the cell; none of the descriptions need one.
            cell = description.replace("|", "/")
            lines.append(f"| `{field.name}` | {_arrow_type_name(field.type)} | {required} | {cell} |")
    return "\n".join([*lines, ""])


### Entry point ###
def _expected_partials() -> dict[Path, str]:
    """Map each generated partial to its expected content."""
    grouped = _module_tables()
    table_names = {table.name for tables in grouped.values() for table in tables}
    partials = {
        PARTIALS_DIR / f"{module.slug}.generated.mdx": _render_diagram_partial(module, tables, table_names)
        for module, tables in grouped.items()
    }
    partials[PARTIALS_DIR / "codebook.generated.mdx"] = _render_codebook()
    return partials


def export_datamodel_partials() -> None:
    """Write the generated docs partials to their output paths."""
    for path, content in _expected_partials().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def partials_are_current() -> bool:
    """Return whether all generated partials are current."""
    return all(
        path.exists() and path.read_text(encoding="utf-8") == expected
        for path, expected in _expected_partials().items()
    )


def main() -> int:
    """Command-line entry point for export and drift checks."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated partials are stale.")
    args = parser.parse_args()

    if args.check:
        return 0 if partials_are_current() else 1

    export_datamodel_partials()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
